name: React CI/CD Pipeline

# This triggers the workflow on pushes and pull requests to the main branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # Job to build and test the application
jobs:
  eslint:
    name: Check Syntax with ESLint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Use Node.js ${{ matrix.node-version }} to Check Lint
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Run ESLint
        run: npm run lint

  tests:
    name: Run Tests
    needs: eslint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Use Node.js 18.x to run Test
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Run Tests
        run: npm run test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Use Node.js 18.x to run Test
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm install
        
      - name: Run Tests
        run: npm run test

      - name: Build the app
        run: npm run build  # Builds the React app for production
  # Job to deploy the application after build
  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensures the deploy job runs only after the build job completes successfully

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Re-checks out the code for deployment

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}  # Pulls Vercel token from GitHub secrets
        run: npx vercel --prod --yes --token $VERCEL_TOKEN 
        #run: npx vercel --prod  # Runs the Vercel deployment in production mode
        #env:
        #  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}  # Uses the Vercel token from GitHub Secrets
